# Generated by Django 3.0.8 on 2020-08-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myawsmCart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
